git add     app/src/main/java/com/example/android/sunshine/app/DetailFragment.java
git add     app/src/main/res/drawable-hdpi/art_clear.png
git add     app/src/main/res/drawable-hdpi/art_clouds.png
git add     app/src/main/res/drawable-hdpi/art_fog.png
git add     app/src/main/res/drawable-hdpi/art_light_clouds.png
git add     app/src/main/res/drawable-hdpi/art_light_rain.png
git add     app/src/main/res/drawable-hdpi/art_rain.png
git add     app/src/main/res/drawable-hdpi/art_snow.png
git add     app/src/main/res/drawable-hdpi/art_storm.png
git add     app/src/main/res/drawable-hdpi/ic_clear.png
git add     app/src/main/res/drawable-hdpi/ic_cloudy.png
git add     app/src/main/res/drawable-hdpi/ic_fog.png
git add     app/src/main/res/drawable-hdpi/ic_light_clouds.png
git add     app/src/main/res/drawable-hdpi/ic_light_rain.png
git add     app/src/main/res/drawable-hdpi/ic_logo.png
git add     app/src/main/res/drawable-hdpi/ic_rain.png
git add     app/src/main/res/drawable-hdpi/ic_snow.png
git add     app/src/main/res/drawable-hdpi/ic_storm.png
git add     app/src/main/res/drawable-mdpi/art_clear.png
git add     app/src/main/res/drawable-mdpi/art_clouds.png
git add     app/src/main/res/drawable-mdpi/art_fog.png
git add     app/src/main/res/drawable-mdpi/art_light_clouds.png
git add     app/src/main/res/drawable-mdpi/art_light_rain.png
git add     app/src/main/res/drawable-mdpi/art_rain.png
git add     app/src/main/res/drawable-mdpi/art_snow.png
git add     app/src/main/res/drawable-mdpi/art_storm.png
git add     app/src/main/res/drawable-mdpi/ic_clear.png
git add     app/src/main/res/drawable-mdpi/ic_cloudy.png
git add     app/src/main/res/drawable-mdpi/ic_fog.png
git add     app/src/main/res/drawable-mdpi/ic_light_clouds.png
git add     app/src/main/res/drawable-mdpi/ic_light_rain.png
git add     app/src/main/res/drawable-mdpi/ic_logo.png
git add     app/src/main/res/drawable-mdpi/ic_rain.png
git add     app/src/main/res/drawable-mdpi/ic_snow.png
git add     app/src/main/res/drawable-mdpi/ic_storm.png
git add     app/src/main/res/drawable-xhdpi/art_clear.png
git add     app/src/main/res/drawable-xhdpi/art_clouds.png
git add     app/src/main/res/drawable-xhdpi/art_fog.png
git add     app/src/main/res/drawable-xhdpi/art_light_clouds.png
git add     app/src/main/res/drawable-xhdpi/art_light_rain.png
git add     app/src/main/res/drawable-xhdpi/art_rain.png
git add     app/src/main/res/drawable-xhdpi/art_snow.png
git add     app/src/main/res/drawable-xhdpi/art_storm.png
git add     app/src/main/res/drawable-xhdpi/ic_clear.png
git add     app/src/main/res/drawable-xhdpi/ic_cloudy.png
git add     app/src/main/res/drawable-xhdpi/ic_fog.png
git add     app/src/main/res/drawable-xhdpi/ic_light_clouds.png
git add     app/src/main/res/drawable-xhdpi/ic_light_rain.png
git add     app/src/main/res/drawable-xhdpi/ic_logo.png
git add     app/src/main/res/drawable-xhdpi/ic_rain.png
git add     app/src/main/res/drawable-xhdpi/ic_snow.png
git add     app/src/main/res/drawable-xhdpi/ic_storm.png
git add     app/src/main/res/drawable-xxhdpi/art_clear.png
git add     app/src/main/res/drawable-xxhdpi/art_clouds.png
git add     app/src/main/res/drawable-xxhdpi/art_fog.png
git add     app/src/main/res/drawable-xxhdpi/art_light_clouds.png
git add     app/src/main/res/drawable-xxhdpi/art_light_rain.png
git add     app/src/main/res/drawable-xxhdpi/art_rain.png
git add     app/src/main/res/drawable-xxhdpi/art_snow.png
git add     app/src/main/res/drawable-xxhdpi/art_storm.png
git add     app/src/main/res/drawable-xxhdpi/ic_clear.png
git add     app/src/main/res/drawable-xxhdpi/ic_cloudy.png
git add     app/src/main/res/drawable-xxhdpi/ic_fog.png
git add     app/src/main/res/drawable-xxhdpi/ic_light_clouds.png
git add     app/src/main/res/drawable-xxhdpi/ic_light_rain.png
git add     app/src/main/res/drawable-xxhdpi/ic_logo.png
git add     app/src/main/res/drawable-xxhdpi/ic_rain.png
git add     app/src/main/res/drawable-xxhdpi/ic_snow.png
git add     app/src/main/res/drawable-xxhdpi/ic_storm.png
git add     app/src/main/res/mipmap-hdpi/
git add     app/src/main/res/mipmap-mdpi/
git add     app/src/main/res/mipmap-xhdpi/
git add     app/src/main/res/mipmap-xxhdpi/
git add     app/src/main/res/mipmap-xxxhdpi/
